

services:
  postgres:
    image: postgres:18
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/pgdata
    networks:
      - payment-network

  payment-service:
    build:
      context: .
    container_name: payment-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      LOG_LEVEL: WARN
      # Connection string Azure Monitor (Azure Portal → Application Insights → Vue d'ensemble)
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=e0c8cd17-481d-4731-9cf3-f88f06152d53;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=754d7d60-7e60-4a96-a291-9da7e6d1d1d6"




    ports:
      - "8082:8082"
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge

volumes:
  postgres_data: