version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/pgdata
    networks:
      - payment-network

  payment-service:
    build: .
    container_name: payment-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_db
      # SPRING_DATASOURCE_USERNAME: postgres
      # SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8082:8082"
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge

volumes:
  postgres_data: