apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap | nindent 2 }}
