apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
