# Application - Configuration commune
spring.application.name=payment-service

# JPA - Configuration commune
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging - Niveau par défaut
logging.level.com.ecommerce.paymentservice=INFO

# le profil dev par défaut
spring.profiles.active=dev

# ou avec VarEnv SPRING_PROFILES_ACTIVE=dev


# Swagger/OpenAPI Configuration
# Swagger/OpenAPI Configuration - Version corrigée
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.packages-to-scan=com.ecommerce.paymentservice
springdoc.paths-to-match=/api/**