# Serveur
server.port=8082

# PostgreSQL - Base locale
spring.datasource.url=jdbc:postgresql://postgres:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - Dev (affiche les requêtes SQL)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging - Dev (détaillé)
logging.level.com.ecommerce.paymentservice=DEBUG
logging.level.org.springframework.web=DEBUG

# Simulation paiement (80% succès)
payment.simulation.success-probability=0.8


# CORS Configuration for Development
cors.allowed-origins=*
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
cors.allowed-headers=*
cors.allow-credentials=true
cors.mapping-path=/api/**