apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.netpolicies.ingresssources }}
      ports:
        - port: {{ .Values.netpolicies.ingressdestports }}
          protocol: {{ .Values.netpolicies.ingressprotocol }}
  egress:
    # pgcat pour les requêtes applicatives (lectures via replicas)
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.netpolicies.egresssources }}
      ports:
        - port: {{ .Values.netpolicies.egressdestports }}
          protocol: {{ .Values.netpolicies.egressprotocol }}
    # postgres-primary pour les migrations (initContainer)
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - port: {{ .Values.netpolicies.egressdestports }}
          protocol: {{ .Values.netpolicies.egressprotocol }}
    # Application Insights
    - ports:
        - port: {{ .Values.netpolicies.httpsinternetports }}
          protocol: {{ .Values.netpolicies.httpsprotocol }}
