image:
  repository: docker.io/jubatouam/payment
  tag: "2.0"
  pullPolicy: Always

replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: 0

affinity:
  nodepool: apps

service:
  type: ClusterIP
  port: 8082

probes:
  path: /api/health
  startup:
    periodSeconds: 10
    failureThreshold: 18
  liveness:
    periodSeconds: 30
    failureThreshold: 3
  readiness:
    periodSeconds: 15
    failureThreshold: 3

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

configmap:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: ""
  LOG_LEVEL: "WARN"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "0.3"

secret:
  enabled: false
  data: {}

initContainer:
  env: []

pdb:
  minAvailable: 1

hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60

ingress:
  enabled: true
  name: ecommerce-ingress
  className: kong
  annotations: {}
  routes:
    - path: /api/payments
      pathType: Prefix
      service:
        name: payment
        port: 8082

externalSecret:
  enabled: false
  refreshInterval: "1m"
  vaultPath: ""

netpolicies:
  ingresssources: kong
  ingressdestports: 8082
  ingressprotocol: TCP
  egresssources: pgcat
  egressdestports: 5432
  egressprotocol: TCP
  httpsinternetports: 443
  httpsprotocol: TCP

vpa:
  enabled: false
  updateMode: "Off"
